/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import SerVic.AccountServic;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Admin
 */
public class FormLogin extends javax.swing.JPanel {
    CardLayout card;
    private AccountServic accountServic;
    private JPanel parentpn;
    private JDialog jDialog;
    /**
     * Creates new form FormLogin
     */
    public FormLogin(CardLayout card,AccountServic account,JPanel pn,JDialog parentdialog) {
        initComponents();
        this.card = card;
        this.accountServic = account;
        this.parentpn = pn;
        jDialog = parentdialog;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnthoat = new javax.swing.JButton();
        btndangnhap = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtgmail = new javax.swing.JTextField();
        txtmatkhau = new javax.swing.JPasswordField();
        lbldangky = new javax.swing.JLabel();
        lblquenmatkhau = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(600, 450));

        pnlogin.setBackground(new java.awt.Color(255, 255, 255));
        pnlogin.setForeground(new java.awt.Color(153, 153, 153));
        pnlogin.setMaximumSize(new java.awt.Dimension(600, 450));
        pnlogin.setPreferredSize(new java.awt.Dimension(600, 450));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Gmail");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Mật Khẩu");

        btnthoat.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnthoat.setText("Thoát");
        btnthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthoatActionPerformed(evt);
            }
        });

        btndangnhap.setBackground(new java.awt.Color(204, 204, 204));
        btndangnhap.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btndangnhap.setText("Đăng Nhập");
        btndangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndangnhapActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Đăng Nhập");

        txtgmail.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtgmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtgmailKeyPressed(evt);
            }
        });

        txtmatkhau.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtmatkhau.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtmatkhauKeyPressed(evt);
            }
        });

        lbldangky.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbldangky.setText("Bạn Chưa Có Tài Khoản ?");
        lbldangky.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbldangkyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbldangkyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbldangkyMouseExited(evt);
            }
        });

        lblquenmatkhau.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblquenmatkhau.setText("Quên Mật Khẩu ?");
        lblquenmatkhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblquenmatkhauMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblquenmatkhauMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblquenmatkhauMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnloginLayout = new javax.swing.GroupLayout(pnlogin);
        pnlogin.setLayout(pnloginLayout);
        pnloginLayout.setHorizontalGroup(
            pnloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnloginLayout.createSequentialGroup()
                .addGroup(pnloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnloginLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnthoat))
                    .addGroup(pnloginLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(pnloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(48, 48, 48)
                        .addGroup(pnloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtmatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtgmail, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btndangnhap)
                            .addComponent(lbldangky)
                            .addComponent(lblquenmatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(146, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnloginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(197, 197, 197))
        );
        pnloginLayout.setVerticalGroup(
            pnloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnloginLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addGap(35, 35, 35)
                .addGroup(pnloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtgmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pnloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(44, 44, 44)
                .addGroup(pnloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndangnhap)
                    .addComponent(btnthoat))
                .addGap(46, 46, 46)
                .addComponent(lbldangky)
                .addGap(40, 40, 40)
                .addComponent(lblquenmatkhau)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(pnlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnthoatActionPerformed

    private void lbldangkyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldangkyMouseClicked
        // TODO add your handling code here:
        showlayout("signup");
    }//GEN-LAST:event_lbldangkyMouseClicked

    private void lbldangkyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldangkyMouseEntered
        // TODO add your handling code here:
        setcolorlblmouseHover(lbldangky);
    }//GEN-LAST:event_lbldangkyMouseEntered

    private void lbldangkyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldangkyMouseExited
        // TODO add your handling code here:
        setcolorlblmouseOut(lbldangky);
    }//GEN-LAST:event_lbldangkyMouseExited

    private void lblquenmatkhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblquenmatkhauMouseClicked
        // TODO add your handling code here:
        showlayout("quenmatkhau");
    }//GEN-LAST:event_lblquenmatkhauMouseClicked

    private void lblquenmatkhauMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblquenmatkhauMouseEntered
        // TODO add your handling code here:
        setcolorlblmouseHover(lblquenmatkhau);
    }//GEN-LAST:event_lblquenmatkhauMouseEntered

    private void lblquenmatkhauMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblquenmatkhauMouseExited
        // TODO add your handling code here:
        setcolorlblmouseOut(lblquenmatkhau);
    }//GEN-LAST:event_lblquenmatkhauMouseExited

    private void btndangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndangnhapActionPerformed
        // TODO add your handling code here:
        login();
    }//GEN-LAST:event_btndangnhapActionPerformed

    private void txtmatkhauKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmatkhauKeyPressed
        // TODO add your handling code here:
        enterkeyLogin(evt);
    }//GEN-LAST:event_txtmatkhauKeyPressed

    private void txtgmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgmailKeyPressed
        // TODO add your handling code here:
        enterkeyLogin(evt);
    }//GEN-LAST:event_txtgmailKeyPressed
    
    void enterkeyLogin(KeyEvent evt){
    if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        login();
        }
    }
    
    void login(){
    if(accountServic.login(txtgmail.getText(), txtmatkhau.getPassword(), parentpn)){
        jDialog.dispose();
        }
    }
    void showlayout(String cardName){
        card.show(parentpn, cardName);
    }
    
    void setcolorlblmouseHover(JLabel lbl){
    lbl.setForeground(Color.gray);
    }
    void setcolorlblmouseOut(JLabel lbl){
    lbl.setForeground(Color.black);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndangnhap;
    private javax.swing.JButton btnthoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbldangky;
    private javax.swing.JLabel lblquenmatkhau;
    private javax.swing.JPanel pnlogin;
    private javax.swing.JTextField txtgmail;
    private javax.swing.JPasswordField txtmatkhau;
    // End of variables declaration//GEN-END:variables
}
