/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import SerVic.AccountServic;
import Util.MessageConfig;
import Util.RegexPattern;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Admin
 */
public class FormQuenMatKhau extends javax.swing.JPanel {

    CardLayout card;
    private AccountServic accountServic;
    private JPanel parentpn;
    private FormXacNhan xacNhan;

    /**
     * Creates new form FormQuenMatKhau
     */
    public FormQuenMatKhau(CardLayout card, AccountServic account, JPanel pn,FormXacNhan xacnhan) {
        initComponents();
        this.card = card;
        this.accountServic = account;
        this.parentpn = pn;
        xacNhan = xacnhan;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnmisspass = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        lbldangnhap = new javax.swing.JLabel();
        lbldangky = new javax.swing.JLabel();
        btnguimaxacnhan = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(600, 450));

        pnmisspass.setBackground(new java.awt.Color(255, 255, 255));
        pnmisspass.setMaximumSize(new java.awt.Dimension(600, 450));
        pnmisspass.setPreferredSize(new java.awt.Dimension(600, 450));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("Quên Mật Khẩu");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Bạn Sẽ Nhận Được Mã Xác Nhận Tại Tài Khoản Gmail Của Mình");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setText("Gmail");

        txtemail.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        lbldangnhap.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbldangnhap.setText("Đăng Nhập Ngay ?");
        lbldangnhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbldangnhapMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbldangnhapMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbldangnhapMouseExited(evt);
            }
        });

        lbldangky.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbldangky.setText("Bạn Chưa Có Tài Khoản ?");
        lbldangky.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbldangkyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbldangkyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbldangkyMouseExited(evt);
            }
        });

        btnguimaxacnhan.setBackground(new java.awt.Color(204, 204, 204));
        btnguimaxacnhan.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnguimaxacnhan.setText("Gửi Mã Xác Nhận");
        btnguimaxacnhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguimaxacnhanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnmisspassLayout = new javax.swing.GroupLayout(pnmisspass);
        pnmisspass.setLayout(pnmisspassLayout);
        pnmisspassLayout.setHorizontalGroup(
            pnmisspassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnmisspassLayout.createSequentialGroup()
                .addGroup(pnmisspassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnmisspassLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addGroup(pnmisspassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnmisspassLayout.createSequentialGroup()
                                .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnguimaxacnhan))
                            .addGroup(pnmisspassLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel10))))
                    .addGroup(pnmisspassLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(pnmisspassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnmisspassLayout.createSequentialGroup()
                                .addComponent(lbldangnhap)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbldangky))
                            .addComponent(jLabel11))))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        pnmisspassLayout.setVerticalGroup(
            pnmisspassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnmisspassLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel10)
                .addGap(91, 91, 91)
                .addGroup(pnmisspassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnguimaxacnhan))
                .addGap(54, 54, 54)
                .addComponent(jLabel11)
                .addGap(60, 60, 60)
                .addGroup(pnmisspassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldangnhap)
                    .addComponent(lbldangky))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnmisspass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnmisspass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lbldangnhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldangnhapMouseClicked
        // TODO add your handling code here:
        showlayout("login");
    }//GEN-LAST:event_lbldangnhapMouseClicked

    private void lbldangnhapMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldangnhapMouseEntered
        // TODO add your handling code here:
        setcolorlblmouseHover(lbldangnhap);
    }//GEN-LAST:event_lbldangnhapMouseEntered

    private void lbldangnhapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldangnhapMouseExited
        // TODO add your handling code here:
        setcolorlblmouseOut(lbldangnhap);
    }//GEN-LAST:event_lbldangnhapMouseExited

    private void lbldangkyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldangkyMouseClicked
        // TODO add your handling code here:
        showlayout("signup");
    }//GEN-LAST:event_lbldangkyMouseClicked

    private void lbldangkyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldangkyMouseEntered
        // TODO add your handling code here:
        setcolorlblmouseHover(lbldangky);
    }//GEN-LAST:event_lbldangkyMouseEntered

    private void lbldangkyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldangkyMouseExited
        // TODO add your handling code here:
        setcolorlblmouseOut(lbldangky);
    }//GEN-LAST:event_lbldangkyMouseExited

    private void btnguimaxacnhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguimaxacnhanActionPerformed
        // TODO add your handling code here:
        guimaxacnhan();
    }//GEN-LAST:event_btnguimaxacnhanActionPerformed

    void guimaxacnhan() {
        String email = txtemail.getText();
        if (email.equals("")) {
            MessageConfig.messageText("Email Không Được Để Trống", parentpn);
        } else if (!RegexPattern.checkgmail(email)) {
            MessageConfig.messageText("Email Không Đúng Định Dạng", parentpn);
        } else if (accountServic.selectFindOneServic(email) == null) {
            MessageConfig.messageText("Gmail Không có trong hệ thống", parentpn);
        }else{
            accountServic.guimaxacnhan(email);
            xacNhan.setgmaillbl(email);
            xacNhan.actiontimeOut();
            showlayout("xacnhan");
        }
    }

    void showlayout(String cardName) {
        card.show(parentpn, cardName);
    }

    void setcolorlblmouseHover(JLabel lbl) {
        lbl.setForeground(Color.gray);
    }

    void setcolorlblmouseOut(JLabel lbl) {
        lbl.setForeground(Color.black);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnguimaxacnhan;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel lbldangky;
    private javax.swing.JLabel lbldangnhap;
    private javax.swing.JPanel pnmisspass;
    private javax.swing.JTextField txtemail;
    // End of variables declaration//GEN-END:variables
}
