/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Model.TaiKhoanModel;
import SerVic.AccountServic;
import Util.MessageConfig;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Admin
 */
public class FormSignUp extends javax.swing.JPanel {

    CardLayout card;
    private AccountServic accountServic;
    private JPanel parentpn;

    /**
     * Creates new form FormSignUp
     */
    public FormSignUp(CardLayout card, AccountServic account, JPanel pn) {
        initComponents();
        this.card = card;
        this.accountServic = account;
        this.parentpn = pn;
        rbtnnam.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngroupGioiTInh = new javax.swing.ButtonGroup();
        pnsignup = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btndangky = new javax.swing.JButton();
        btnthoat = new javax.swing.JButton();
        rbtnnam = new javax.swing.JRadioButton();
        rbtnnu = new javax.swing.JRadioButton();
        txtgmail = new javax.swing.JTextField();
        txtxacnhanmatkhau = new javax.swing.JPasswordField();
        txtmatkhau = new javax.swing.JPasswordField();
        txtten = new javax.swing.JTextField();
        lbldangnhap = new javax.swing.JLabel();
        lblquenmk = new javax.swing.JLabel();

        btngroupGioiTInh.add(rbtnnam);
        btngroupGioiTInh.add(rbtnnu);

        setPreferredSize(new java.awt.Dimension(600, 450));

        pnsignup.setBackground(new java.awt.Color(255, 255, 255));
        pnsignup.setMaximumSize(new java.awt.Dimension(600, 450));
        pnsignup.setPreferredSize(new java.awt.Dimension(600, 350));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Đăng Ký");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Gmail");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Mật Khẩu");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Xác Nhận Mật Khẩu");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("Tên");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("Giới Tính");

        btndangky.setBackground(new java.awt.Color(204, 204, 204));
        btndangky.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btndangky.setText("Đăng Ký");
        btndangky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndangkyActionPerformed(evt);
            }
        });

        btnthoat.setBackground(new java.awt.Color(204, 204, 204));
        btnthoat.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnthoat.setText("Thoát");
        btnthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthoatActionPerformed(evt);
            }
        });

        rbtnnam.setBackground(new java.awt.Color(255, 255, 255));
        rbtnnam.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        rbtnnam.setText("Nam");

        rbtnnu.setBackground(new java.awt.Color(255, 255, 255));
        rbtnnu.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        rbtnnu.setText("Nữ");

        txtgmail.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        txtxacnhanmatkhau.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        txtmatkhau.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        txtten.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        lbldangnhap.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbldangnhap.setText("Đăng Nhập Ngay ?");
        lbldangnhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbldangnhapMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbldangnhapMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbldangnhapMouseExited(evt);
            }
        });

        lblquenmk.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblquenmk.setText("Quên Mật Khẩu ?");
        lblquenmk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblquenmkMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblquenmkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblquenmkMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnsignupLayout = new javax.swing.GroupLayout(pnsignup);
        pnsignup.setLayout(pnsignupLayout);
        pnsignupLayout.setHorizontalGroup(
            pnsignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnsignupLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(239, 239, 239))
            .addGroup(pnsignupLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(pnsignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(pnsignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnsignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(pnsignupLayout.createSequentialGroup()
                            .addComponent(btndangky)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnthoat))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnsignupLayout.createSequentialGroup()
                            .addComponent(rbtnnam)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbtnnu))
                        .addComponent(txtmatkhau, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtxacnhanmatkhau, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtgmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtten, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnsignupLayout.createSequentialGroup()
                        .addComponent(lbldangnhap)
                        .addGap(64, 64, 64)
                        .addComponent(lblquenmk)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        pnsignupLayout.setVerticalGroup(
            pnsignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnsignupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(29, 29, 29)
                .addGroup(pnsignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtgmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pnsignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtmatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(pnsignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtxacnhanmatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pnsignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(pnsignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(rbtnnam)
                    .addComponent(rbtnnu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(pnsignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndangky)
                    .addComponent(btnthoat))
                .addGap(18, 18, 18)
                .addGroup(pnsignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldangnhap)
                    .addComponent(lblquenmk))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnsignup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnsignup, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lbldangnhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldangnhapMouseClicked
        // TODO add your handling code here:
        showlayout("login");
    }//GEN-LAST:event_lbldangnhapMouseClicked

    private void lbldangnhapMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldangnhapMouseEntered
        // TODO add your handling code here:
        setcolorlblmouseHover(lbldangnhap);
    }//GEN-LAST:event_lbldangnhapMouseEntered

    private void lbldangnhapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldangnhapMouseExited
        // TODO add your handling code here:
        setcolorlblmouseOut(lbldangnhap);
    }//GEN-LAST:event_lbldangnhapMouseExited

    private void lblquenmkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblquenmkMouseClicked
        // TODO add your handling code here:
        showlayout("quenmatkhau");
    }//GEN-LAST:event_lblquenmkMouseClicked

    private void lblquenmkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblquenmkMouseEntered
        // TODO add your handling code here:
        setcolorlblmouseHover(lblquenmk);
    }//GEN-LAST:event_lblquenmkMouseEntered

    private void lblquenmkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblquenmkMouseExited
        // TODO add your handling code here:
        setcolorlblmouseOut(lblquenmk);
    }//GEN-LAST:event_lblquenmkMouseExited

    private void btndangkyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndangkyActionPerformed
        // TODO add your handling code here:
        TaiKhoanModel taikhoan = new TaiKhoanModel(txtgmail.getText(), txtten.getText(), String.valueOf(txtmatkhau.getPassword()), rbtnnam.isSelected() ? "nam" : "nữ");
        if (accountServic.signup(taikhoan, parentpn, txtxacnhanmatkhau.getPassword())) {
            MessageConfig.messageText("Đăng Ký Thành Công", parentpn);
            showlayout("login");
        }
    }//GEN-LAST:event_btndangkyActionPerformed

    private void btnthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnthoatActionPerformed
    
    void showlayout(String cardName) {
        card.show(parentpn, cardName);
    }

    void setcolorlblmouseHover(JLabel lbl) {
        lbl.setForeground(Color.gray);
    }

    void setcolorlblmouseOut(JLabel lbl) {
        lbl.setForeground(Color.black);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndangky;
    private javax.swing.ButtonGroup btngroupGioiTInh;
    private javax.swing.JButton btnthoat;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbldangnhap;
    private javax.swing.JLabel lblquenmk;
    private javax.swing.JPanel pnsignup;
    private javax.swing.JRadioButton rbtnnam;
    private javax.swing.JRadioButton rbtnnu;
    private javax.swing.JTextField txtgmail;
    private javax.swing.JPasswordField txtmatkhau;
    private javax.swing.JTextField txtten;
    private javax.swing.JPasswordField txtxacnhanmatkhau;
    // End of variables declaration//GEN-END:variables
}
