/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Util.JDBC;
import Util.cookieNguoiDung;
import Util.formatterImage;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author Admin
 */
public class mainform extends javax.swing.JFrame {

    /**
     * Creates new form mainform
     */
    public mainform() throws ClassNotFoundException, SQLException {
        initComponents();
        JDBC.con = JDBC.getconnect();
        new loginParent(this, rootPaneCheckingEnabled).setVisible(rootPaneCheckingEnabled);
        init();
    }

    void init() {
        setLocationRelativeTo(null);
        seticon();
    }

    void seticon() {
        lbltoan.setIcon(formatterImage.fiximage("src\\icon\\toan.jpg"));
        lbldia.setIcon(formatterImage.fiximage("src\\icon\\dialy.jpg"));
        lblgdcd.setIcon(formatterImage.fiximage("src\\icon\\gdcd.jpg"));
        lblhoa.setIcon(formatterImage.fiximage("src\\icon\\hoahoc.jpg"));
        lbltienganh.setIcon(formatterImage.fiximage("src\\icon\\tienganh.jpg"));
        lblly.setIcon(formatterImage.fiximage("src\\icon\\vatly.jpg"));
        lblsinh.setIcon(formatterImage.fiximage("src\\icon\\sinhhoc.jpg"));
        lblsu.setIcon(formatterImage.fiximage("src\\icon\\lichsu.jpg"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btndangxuat = new javax.swing.JButton();
        btncaudethiyeuthich = new javax.swing.JButton();
        btnbieudo = new javax.swing.JButton();
        btnthoat = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbltoan = new javax.swing.JLabel();
        btntoan = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnly = new javax.swing.JButton();
        lblly = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnhoa = new javax.swing.JButton();
        lblhoa = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnsinh = new javax.swing.JButton();
        lblsinh = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnlichsu = new javax.swing.JButton();
        lblsu = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btndialy = new javax.swing.JButton();
        lbldia = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        btnGDCD = new javax.swing.JButton();
        lblgdcd = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        btntienganh = new javax.swing.JButton();
        lbltienganh = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jToolBar1.setBackground(new java.awt.Color(204, 204, 204));
        jToolBar1.setRollover(true);
        jToolBar1.setMargin(new java.awt.Insets(0, 20, 20, 0));

        btndangxuat.setBackground(new java.awt.Color(204, 204, 204));
        btndangxuat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btndangxuat.setText("Đăng Xuất");
        btndangxuat.setFocusable(false);
        btndangxuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btndangxuat.setMargin(new java.awt.Insets(25, 25, 25, 25));
        btndangxuat.setPreferredSize(new java.awt.Dimension(200, 150));
        btndangxuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btndangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndangxuatActionPerformed(evt);
            }
        });
        jToolBar1.add(btndangxuat);

        btncaudethiyeuthich.setBackground(new java.awt.Color(204, 204, 204));
        btncaudethiyeuthich.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btncaudethiyeuthich.setText("Câu Hỏi  Yêu Thích");
        btncaudethiyeuthich.setFocusable(false);
        btncaudethiyeuthich.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btncaudethiyeuthich.setMargin(new java.awt.Insets(25, 25, 25, 25));
        btncaudethiyeuthich.setPreferredSize(new java.awt.Dimension(200, 150));
        btncaudethiyeuthich.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btncaudethiyeuthich);

        btnbieudo.setBackground(new java.awt.Color(204, 204, 204));
        btnbieudo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnbieudo.setText("Xem Biểu Đồ");
        btnbieudo.setFocusable(false);
        btnbieudo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnbieudo.setMargin(new java.awt.Insets(25, 25, 25, 25));
        btnbieudo.setPreferredSize(new java.awt.Dimension(200, 150));
        btnbieudo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnbieudo);

        btnthoat.setBackground(new java.awt.Color(204, 204, 204));
        btnthoat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnthoat.setText("Thoát");
        btnthoat.setFocusable(false);
        btnthoat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnthoat.setMargin(new java.awt.Insets(25, 25, 25, 25));
        btnthoat.setPreferredSize(new java.awt.Dimension(200, 150));
        btnthoat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnthoat);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        jPanel2.setPreferredSize(new java.awt.Dimension(250, 215));

        lbltoan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbltoan.setForeground(new java.awt.Color(153, 153, 153));
        lbltoan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltoan.setText("Môn Toán");
        lbltoan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbltoan.setPreferredSize(new java.awt.Dimension(130, 120));
        lbltoan.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        btntoan.setBackground(new java.awt.Color(255, 255, 255));
        btntoan.setForeground(new java.awt.Color(51, 153, 255));
        btntoan.setText("Xem Chi Tiết");
        btntoan.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 153, 255), null));
        btntoan.setMargin(new java.awt.Insets(10, 10, 10, 10));
        btntoan.setPreferredSize(new java.awt.Dimension(100, 35));
        btntoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntoanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(btntoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbltoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltoan, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btntoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        jPanel3.setPreferredSize(new java.awt.Dimension(250, 215));

        btnly.setBackground(new java.awt.Color(255, 255, 255));
        btnly.setForeground(new java.awt.Color(51, 153, 255));
        btnly.setText("Xem Chi Tiết");
        btnly.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 153, 255), null));
        btnly.setMargin(new java.awt.Insets(10, 10, 10, 10));
        btnly.setPreferredSize(new java.awt.Dimension(100, 35));
        btnly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlyActionPerformed(evt);
            }
        });

        lblly.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblly.setForeground(new java.awt.Color(153, 153, 153));
        lblly.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblly.setText("Vật Lý");
        lblly.setToolTipText("");
        lblly.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblly.setPreferredSize(new java.awt.Dimension(130, 120));
        lblly.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(btnly, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(lblly, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblly, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnly, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        jPanel4.setPreferredSize(new java.awt.Dimension(250, 215));

        btnhoa.setBackground(new java.awt.Color(255, 255, 255));
        btnhoa.setForeground(new java.awt.Color(51, 153, 255));
        btnhoa.setText("Xem Chi Tiết");
        btnhoa.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 153, 255), null));
        btnhoa.setMargin(new java.awt.Insets(10, 10, 10, 10));
        btnhoa.setPreferredSize(new java.awt.Dimension(100, 35));
        btnhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhoaActionPerformed(evt);
            }
        });

        lblhoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblhoa.setForeground(new java.awt.Color(153, 153, 153));
        lblhoa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblhoa.setText("Hóa Học");
        lblhoa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblhoa.setPreferredSize(new java.awt.Dimension(130, 120));
        lblhoa.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(lblhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblhoa, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        jPanel5.setPreferredSize(new java.awt.Dimension(250, 215));

        btnsinh.setBackground(new java.awt.Color(255, 255, 255));
        btnsinh.setForeground(new java.awt.Color(51, 153, 255));
        btnsinh.setText("Xem Chi Tiết");
        btnsinh.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 153, 255), null));
        btnsinh.setMargin(new java.awt.Insets(10, 10, 10, 10));
        btnsinh.setPreferredSize(new java.awt.Dimension(100, 35));
        btnsinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsinhActionPerformed(evt);
            }
        });

        lblsinh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblsinh.setForeground(new java.awt.Color(153, 153, 153));
        lblsinh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblsinh.setText("Sinh Học");
        lblsinh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblsinh.setPreferredSize(new java.awt.Dimension(130, 120));
        lblsinh.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(btnsinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(lblsinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblsinh, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnsinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        jPanel6.setPreferredSize(new java.awt.Dimension(250, 215));

        btnlichsu.setBackground(new java.awt.Color(255, 255, 255));
        btnlichsu.setForeground(new java.awt.Color(51, 153, 255));
        btnlichsu.setText("Xem Chi Tiết");
        btnlichsu.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 153, 255), null));
        btnlichsu.setMargin(new java.awt.Insets(10, 10, 10, 10));
        btnlichsu.setPreferredSize(new java.awt.Dimension(100, 35));
        btnlichsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlichsuActionPerformed(evt);
            }
        });

        lblsu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblsu.setForeground(new java.awt.Color(153, 153, 153));
        lblsu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblsu.setText("Lịch Sử");
        lblsu.setToolTipText("");
        lblsu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblsu.setPreferredSize(new java.awt.Dimension(130, 120));
        lblsu.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(btnlichsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(lblsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblsu, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnlichsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        jPanel7.setPreferredSize(new java.awt.Dimension(250, 215));

        btndialy.setBackground(new java.awt.Color(255, 255, 255));
        btndialy.setForeground(new java.awt.Color(51, 153, 255));
        btndialy.setText("Xem Chi Tiết");
        btndialy.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 153, 255), null));
        btndialy.setMargin(new java.awt.Insets(10, 10, 10, 10));
        btndialy.setPreferredSize(new java.awt.Dimension(100, 35));
        btndialy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndialyActionPerformed(evt);
            }
        });

        lbldia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbldia.setForeground(new java.awt.Color(153, 153, 153));
        lbldia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbldia.setText("Địa Lý");
        lbldia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbldia.setPreferredSize(new java.awt.Dimension(130, 120));
        lbldia.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(btndialy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(lbldia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbldia, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btndialy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        jPanel8.setPreferredSize(new java.awt.Dimension(250, 215));

        btnGDCD.setBackground(new java.awt.Color(255, 255, 255));
        btnGDCD.setForeground(new java.awt.Color(51, 153, 255));
        btnGDCD.setText("Xem Chi Tiết");
        btnGDCD.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 153, 255), null));
        btnGDCD.setMargin(new java.awt.Insets(10, 10, 10, 10));
        btnGDCD.setPreferredSize(new java.awt.Dimension(100, 35));
        btnGDCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGDCDActionPerformed(evt);
            }
        });

        lblgdcd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblgdcd.setForeground(new java.awt.Color(153, 153, 153));
        lblgdcd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblgdcd.setText("GDCD");
        lblgdcd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblgdcd.setPreferredSize(new java.awt.Dimension(130, 120));
        lblgdcd.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGDCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(lblgdcd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblgdcd, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnGDCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        jPanel9.setPreferredSize(new java.awt.Dimension(250, 215));

        btntienganh.setBackground(new java.awt.Color(255, 255, 255));
        btntienganh.setForeground(new java.awt.Color(51, 153, 255));
        btntienganh.setText("Xem Chi Tiết");
        btntienganh.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 153, 255), null));
        btntienganh.setMargin(new java.awt.Insets(10, 10, 10, 10));
        btntienganh.setPreferredSize(new java.awt.Dimension(100, 35));
        btntienganh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntienganhActionPerformed(evt);
            }
        });

        lbltienganh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbltienganh.setForeground(new java.awt.Color(153, 153, 153));
        lbltienganh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltienganh.setText("Tiếng Anh");
        lbltienganh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbltienganh.setPreferredSize(new java.awt.Dimension(130, 120));
        lbltienganh.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltienganh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(btntienganh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltienganh, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btntienganh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Thi Thử THPT Quốc Gia");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(123, 123, 123)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(111, 111, 111)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 1520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(486, 486, 486)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndangxuatActionPerformed
        // TODO add your handling code here:
        logOut();
    }//GEN-LAST:event_btndangxuatActionPerformed

    private void btntoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntoanActionPerformed
        // TODO add your handling code here:
        hienthiDeThiByMonHoc("TOAN");
    }//GEN-LAST:event_btntoanActionPerformed

    private void btnlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlyActionPerformed
        // TODO add your handling code here:
        hienthiDeThiByMonHoc("VAT_LY");
    }//GEN-LAST:event_btnlyActionPerformed

    private void btnhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhoaActionPerformed
        // TODO add your handling code here:
        hienthiDeThiByMonHoc("HOA_HOC");
    }//GEN-LAST:event_btnhoaActionPerformed

    private void btnsinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsinhActionPerformed
        // TODO add your handling code here:
        hienthiDeThiByMonHoc("SINH_HOC");
    }//GEN-LAST:event_btnsinhActionPerformed

    private void btnlichsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlichsuActionPerformed
        // TODO add your handling code here:
        hienthiDeThiByMonHoc("LICH_SU");
    }//GEN-LAST:event_btnlichsuActionPerformed

    private void btndialyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndialyActionPerformed
        // TODO add your handling code here:
        hienthiDeThiByMonHoc("DIA_LY");
    }//GEN-LAST:event_btndialyActionPerformed

    private void btnGDCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGDCDActionPerformed
        // TODO add your handling code here:
        hienthiDeThiByMonHoc("GDCD");
    }//GEN-LAST:event_btnGDCDActionPerformed

    private void btntienganhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntienganhActionPerformed
        // TODO add your handling code here:
        hienthiDeThiByMonHoc("NGOAI_NGU");
    }//GEN-LAST:event_btntienganhActionPerformed

    void logOut() {
        this.dispose();
        cookieNguoiDung.logOut();
        new loginParent(new JFrame(), true).setVisible(true);
    }

    void hienthiDeThiByMonHoc(String mamonhoc) {
        this.dispose();
        new FormChonDeThi(mamonhoc).setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new mainform().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(mainform.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(mainform.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGDCD;
    private javax.swing.JButton btnbieudo;
    private javax.swing.JButton btncaudethiyeuthich;
    private javax.swing.JButton btndangxuat;
    private javax.swing.JButton btndialy;
    private javax.swing.JButton btnhoa;
    private javax.swing.JButton btnlichsu;
    private javax.swing.JButton btnly;
    private javax.swing.JButton btnsinh;
    private javax.swing.JButton btnthoat;
    private javax.swing.JButton btntienganh;
    private javax.swing.JButton btntoan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lbldia;
    private javax.swing.JLabel lblgdcd;
    private javax.swing.JLabel lblhoa;
    private javax.swing.JLabel lblly;
    private javax.swing.JLabel lblsinh;
    private javax.swing.JLabel lblsu;
    private javax.swing.JLabel lbltienganh;
    private javax.swing.JLabel lbltoan;
    // End of variables declaration//GEN-END:variables
}
